# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_number',
            field=models.TextField(unique=True),
        ),
    ]
