# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170917_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
