# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170917_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3000)),
        ),
    ]
