# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_notification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='abstract_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
